destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/lb2-pdf"
port: 4010
output: pdf
product: loopback2
print_title: LoopBack Documentation
print_subtitle: version 2.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
