destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/lb3-pdf"
port: 4011
output: pdf
product: loopback3
print_title: LoopBack documentation
print_subtitle: version 3.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
